# Generated by Django 3.2.8 on 2021-11-13 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('podcastbird657', '0002_auto_20210808_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastfeedbirdpage',
            name='author_link',
        ),
        migrations.RemoveField(
            model_name='podcastfeedbirdpage',
            name='exclude_from_sitemap',
        ),
        migrations.RemoveField(
            model_name='podcastfeedbirdpage',
            name='feed_copyright',
        ),
        migrations.RemoveField(
            model_name='podcastfeedbirdpage',
            name='feed_locked',
        ),
        migrations.RemoveField(
            model_name='podcastfeedbirdpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='podcastfeedbirdpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='podcastfeedbirdpage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='podcastfeedbirdpage',
            name='show_breadcrumbs',
        ),
        migrations.RemoveField(
            model_name='podcastfeedbirdpage',
            name='show_coverImage',
        ),
        migrations.RemoveField(
            model_name='podcastfeedbirdpage',
            name='show_date',
        ),
        migrations.RemoveField(
            model_name='podcastfeedbirdpage',
            name='tags',
        ),
        migrations.AddField(
            model_name='podcastbirdpage',
            name='author_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcastbirdpage',
            name='feed_copyright',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='podcastbirdpage',
            name='feed_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcastbirdpage',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='podcastbirdpage',
            name='language',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='PodCastFeedBirdPageTag',
        ),
    ]
